### ISSUE TITLE
No Account Registration Links Available on Plandex.ai for Plandex Cloud Service

### ISSUE THREAD

**Issue by Tritaya** [plandex-ai/plandex#113]
I was exploring the Plandex Cloud service as outlined on the Plandex.ai website. The service is described as an easy and reliable way to use Plandex. There are no visible links or buttons to register or start a trial on the website.

**Comment by danenania** [comment]
Hi @Tritaya, you can install Plandex as described here: https://github.com/plandex-ai/plandex?tab=readme-ov-file#install

Then run `plandex new` and you will be prompted to start a trial on cloud.
