### ISSUE TITLE
Server error setting max tokens 

### ISSUE THREAD

**Issue by NotBrianZach** [plandex-ai/plandex#121]
plandex set-model 
? Select a role or override to update: ⚙️  override | max-tokens → overall 🪙 limit
✔ Set max-tokens (leave blank for no value) … 30000
🚨 Error updating settings
  → &{other 502 <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html> <nil> <nil>}

**Comment by danenania** [comment]
Hey @NotBrianZach, is this with cloud or a self-hosted server? Are you seeing it repeatably or does it work if you try again?

**Comment by NotBrianZach** [comment]
it worked after I tried again just now, it was with cloud though

**Comment by danenania** [comment]
@NotBrianZach ok, please let me know if it keeps happening... everything is looking fine on the servers, so I'd most likely chalk it up to a random AWS failure.
