### ISSUE TITLE
Add gpt-4o

### ISSUE THREAD

**Issue by mjtechguy** [plandex-ai/plandex#122]
Hello,

How do I add gpt-4o to as the primary instead of gpt-4-turbo? I added a custom model, but I am not sure how to switch.

Thanks!

**Comment by danenania** [comment]
gpt-4o is the new default in [1.0.0](https://github.com/plandex-ai/plandex/releases/tag/server%2Fv1.0.0) but in the future you can set a new model for a role using `plandex set-model`
