### ISSUE TITLE
Error when pointing open ai base url at Ollama. Won’t list Ollama models

### ISSUE THREAD

**Issue by atljoseph** [plandex-ai/plandex#125]
Running with docker compose with start local script. Am all logged in. The env vars are applied to both cli and docker env. Wasn’t really clear from the docs how to debug this. Is there a debug mode? Haven’t delved into the code just yet. Was trying to go by what the docs said. 

![IMG_1791](https://github.com/plandex-ai/plandex/assets/25017621/4192000a-c262-4116-a37c-ad4f136e27e6)
![IMG_1790](https://github.com/plandex-ai/plandex/assets/25017621/0f047da6-af30-4d8c-9cde-d66ceee30b6d)

Was finally able to get it to NOT refuse connection with Ollama, but this came thereafter. Completely blocked from using this beautiful code product.

**Comment by atljoseph** [comment]
this seems to come from an incorrectly configured environment set up in the docker compose file database load the file but the server never loads the EV file. Why is that? Why would it be written like that? Waste hours of peoples time

**Comment by danenania** [comment]
Hey @atljoseph, this was recently updated by a contributor to enable the `start_local.sh` script, so there certainly could be some kinks to work out. It looks like we need `env-file` specified  for the `plandex-server` service as well so that those vars are passed through.

**Comment by danenania** [comment]
@atljoseph `env-file` is now included in the `plandex-server` service, so those vars will now get passed through to the server.
