### ISSUE TITLE
Why is it so hard to add a model from my local Ollama. 

### ISSUE THREAD

**Issue by atljoseph** [plandex-ai/plandex#126]
Why is this so painful? I’m a cli person, but this is near sadistic. Spending longer figuring this out than actually doing useful things. 

When I finally added a custom model and added a model set, it wouldn’t even let me select my custom model for the builder… paid models only? 

Please clearly and concisely list the steps required to configure a local model…. And ACTUALLY USE IT for something. 

I know you’ve put a lot of time and energy into this. That is clear. But if it’s hard to use, people aren’t gonna use it. 

Right now all it has netted is frustration. 

Right now this feels like a play toy

**Comment by atljoseph** [comment]
Perhaps that is by design. To force them to use the paid cloud thing.

**Comment by danenania** [comment]
@atljoseph The builder role requires streaming function calls, which unfortunately are only supported by OpenAI so far.

This is right at the top of the docs:

> While you can now use Plandex with many different providers and models, for some functionality Plandex has requirements that only OpenAI models, for the time being, can satisfy. That means you'll need an OpenAI account to get started even if you plan to use other model providers.

**Comment by danenania** [comment]
@atljoseph  It sounds like you would be better off using cloud (which is free for now). It's designed to make getting started as quick and easy as possible.

While I also want self-hosting to be easy, there are more moving parts and everyone's environment is different, so there are always going to be more potential issues.

Your tone is a bit much btw. This is a free tool, and I'm here on Friday night trying to help you. I'm fine with getting constructive feedback and criticism, but the rudeness is uncalled for. Please be respectful if you're going to continue to participate.

**Comment by atljoseph** [comment]
Dude. Nobody asked you to respond on a Friday night. That was a choice just
like it was a choice for me to waste hours on this and then feel sour about
it later.

**Comment by atljoseph** [comment]
Not interested in the cloud offering in any way

**Comment by atljoseph** [comment]
I was thinking about integrating a UI I’m building with this tool if you
really must know. Was really excited about it. All that steam was lost.
Things don’t need to be this painful. Some people like pain.

**Comment by atljoseph** [comment]
You can call it rude or you can call it real and frustrated. Really, what
have I said here that is a drop in the bucket against anything else out
there?

**Comment by danenania** [comment]
I’ve been building software for a long time and have dealt with thousands of users and many hundreds of bug reports. In all that time, I can count on one hand the number of people that have been rude and disrespectful to me. This includes when there have been bugs in critical systems that have caused major outages. These were situations where people certainly had a justification for being upset, yet they handled it professionally.

Do you really want to be the 1 in 1000 person who acts like a jerk because they had trouble installing some open source software?

**Comment by atljoseph** [comment]
Dont get me wrong. I appreciate the time you put into the software. I’ve
taken the opportunity to mention that numerous times. The proof is the fact
that emotions have been exchanged, and we are emailing right now.

Yeah I can come across rude. One man’s trash is another man’s treasure.
That doesn’t mean the trash is valuable, nor the treasure worthless.
Everybody is different, man. I don’t know what to say. Grow some thicker
skin, maybe?

At any rate, the software looks awesome. I’m just not interested in using
it because it doesn’t fit my use case and I’m soured on the setup pains.

1/1000 sounds too good to be true. But what do I know?

**Comment by atljoseph** [comment]
Because it does look so awesome, and because at some point the function
calling landscape may change, I broke down and tried it with some new
OpenAI api keys. It works pretty well, but can’t seem to ever add any
context files. When I add context files with a relative path from the
project root, it processes something, and says no context loaded. Never
errors out or says a file wasn’t found. As a result after 5+ attempts, it
keeps missing the fact that the ui it is supposed to update is a sunscreen
of a bigger app in the same package, and instead tries to overwrite the
existing file as the ui’s root screen, and in the main package. Very
perplexing. It’s like absolutely no context is being forwarded and it is
merely acting on the instruction as if it were completely greenfield. So,
it isn’t loading context files ? Is it supposed to load any context by
default?

**Comment by atljoseph** [comment]
Apparently I can’t spell and it wasn’t blowing up complaining about no
files found. It’s working now though. With OpenAI

**Comment by atljoseph** [comment]
I do have to apologize for letting my bitterness get the best of me and
being rash with you. I tend to get emotionally attached to code as you can
tell. Thank you do your project.

**Comment by danenania** [comment]
Thank you, I accept the apology. And glad to hear it’s working for you now with OpenAI.

I would like to remove OpenAI as a requirement for builds. It’s a bit complicated as I said due to api compatibility issues, but it will happen at some point.

**Comment by atljoseph** [comment]
I think I might pivot to building a front end for your tool. Everything in
go. Would basically be a functional ui wrapper around it.

**Comment by atljoseph** [comment]
To clarify… a ui app to host the terminal. But also maybe to assist in
building the cli tool with the proper/desired variables, and ui components
to help with inputs… and stay the hell out of the terminal’s way :)

Do you currently have anything cooking in that department? Am currently
building something just far enough along that a pivot won’t matter.

I think a really simple ui would be super helpful for both users themselves
and for broader acceptance.
