### ISSUE TITLE
Edit plan before it's built

### ISSUE THREAD

**Issue by mfclarke** [plandex-ai/plandex#13]
First off, plandex is fantastic. Thank you for open sourcing it!

A few times I've found myself wanting to edit a generated plan before it's built. Things like removing a step, or changing it slightly. For example, when working in a swift codebase and writing unit tests I have wanted it to generate a protocol for the object being mocked rather than use subclassing.

Aborting and editing the "tell" is a bit more cumbersome and indirect.

**Comment by danenania** [comment]
Thanks for the kind words @mfclarke and for the feedback.

Could you walk me through in a bit more detail what kind of workflow you'd like? I'm not sure if I fully understand.

**Comment by mfclarke-cnx** [comment]
Sorry I used the wrong terminology. What I meant was, once a plan has been built, it would be great to edit it before it is executed and file changes are generated.

So in this workflow:
1. Load files
2. Tell Plandex what you want it to do
3. Watch plan get built with multiple steps detailed etc.
4. Watch files changes get generated
5. Apply changes

It would be step 3.5 :) Watch the plan get built, and then be given the opportunity to edit those steps that were generated before the file changes are generated. Just a simple "Proceed with this plan? y/n" and when you press "n" it opens the text editor (like `plandex tell`) with the contents of the plan. You can then edit and refine it if it has made some small mistakes or misunderstandings.

**Comment by danenania** [comment]
Closing for now, but let me know if that doesn't solve it for you and you were thinking of something different.

**Comment by mfclarke-cnx** [comment]
No sorry, that's not quite what I mean. That still goes ahead and writes the code for the outlined steps. It just doesn't build the files themselves. 

It would be great to get a chance to edit plandex's proposal before it is executed on, in cases where plandex misunderstands something or misses an important detail.

For example:

```
 💬 User prompt 👇 

  Add a new formatter that outputs the given number as words. Please write unit
  tests for it as well

 🤖 Plandex reply 👇 

  Let's break up this task.                                                   
                                                                              
  1. Implement a new formatter  NumberAsWordsFormatStyle  that outputs a given
  number as words.                                                            
  2. Write unit tests for the  NumberAsWordsFormatStyle  to ensure it works   
  correctly for various numbers.                                              
                                                                              
  Next, we will start with implementing the new formatter                     
  NumberAsWordsFormatStyle .                                                  
                                                                              
  👉 To implement the new formatter .....
```

If Plandex stops after listing the steps and allows the user to edit them if they wish before continuing, that would be great. They could add some extra detail if needed, or remove an unnecessary step. For example, in step 2, adding "including floating point and negative numbers". It's cumbersome to stop generation, rewind, and reprompt hoping it will get what you mean this time.

**Comment by danenania** [comment]
Oh ok, now I really see what you mean :)  Thanks for explaining--that's an interesting idea. I guess the main way to simulate this currently would be to copy the reply output, edit it, then rewind and just include the edited output in your prompt, but it's definitely a bit cumbersome compared to what you're proposing.
