### ISSUE TITLE
Build plan outputs great code, but when i accept the changes, somehow it only outputted part of the plan.

### ISSUE THREAD

**Issue by atljoseph** [plandex-ai/plandex#130]
Not sure how to diagnose.

Is there a way to go back and have it re-apply the changes or something?

This happened after i broke some large files up into smaller ones, and then re-upped the context with just the 2 files i wanted to change.

Tell me what you need in order to proceed.

**Comment by atljoseph** [comment]
Also how to clear message history on a plan?

**Comment by danenania** [comment]
You can use `plandex log` to see a history of every change, and then `plandex rewind` to go back to whatever point makes sense. Applying changes is part of the log, so you can also undo that in order to reapply the changes. Does that help?

**Comment by atljoseph** [comment]
Yeah. Sometimes it gets confused if I edit something. Aider does that too. I like how plandex at least tries to catch changes on chat exec. I also find remembering the commands and thinking about the code and everything a bit cumbersome. Not that it’s anybody’s fault. It’s the nature of a cli tool. I ended up building a super simple fyne app with embedded terminal. It works. The terminal widget has a super slow startup time and seems to stream the tailed logs back from background process in 1 big chunk. So idk. lol. Might try and figure that out. Or not. Interested in your thoughts. https://github.com/fyne-io/terminal
