### ISSUE TITLE
WSL load context hungs

### ISSUE THREAD

**Issue by msveshnikov** [plandex-ai/plandex#135]
Under WSL, always hungs

PS C:\My-progs\Node.JS\allchat> wsl plandex set-model
? Choose a new model pack, or select a role or override to update: 🤖 role | builder → builds a plan into file diffs
? Select a property to update: Select a model
? Select a provider: openai
? Select a model: openai → gpt-4o-2024-05-13 | max 128000 🪙
⚙️  Updated model settings:
  • model-pack.builder.model-name | gpt-4o → gpt-4o-2024-05-13

 plandex models  👉 show current plan model settings
 plandex set-model default  👉 update org-wide default model settings for new plans
 plandex log  👉 show log of plan updates
PS C:\My-progs\Node.JS\allchat> wsl plandex load server/index.js
📥 Loading context... [==        ]

**Comment by danenania** [comment]
Hey @msveshnikov, it looks like you're using WSL via the Windows CMD prompt. Can you try opening a dedicated WSL terminal instead? Just type 'wsl' into your Windows search bar and press Enter to open the WSL Bash shell.
