### ISSUE TITLE
State that is not in the loaded context seems to affect the quality of changes

### ISSUE THREAD

**Issue by tachyonicbytes** [plandex-ai/plandex#136]
How much state is kept from the conversations?

I call `plandex tell`, plandex codes something, I accept it, I manually remove some parts and save and commit, then, plandex updates the context, but then when I `tell` it something again, it reverts some parts of the code that I manually removed, even if the new question wouldn't have to lead to them being added.

Is there hidden context state somewhere that is not in the files that I call `load` on?

**Comment by danenania** [comment]
I think this is likely coming from the conversation history. I'll work on preventing this behavior.
