### ISSUE TITLE
Continually deletes perfectly good code that is unrelated to the request. 

### ISSUE THREAD

**Issue by atljoseph** [plandex-ai/plandex#137]
I literally have to tell it to be respectful and ask before it deletes any code. There needs to be a system prompt so users don’t have to get so granular. I’m just using gpt4o. When people use this system to help automate the going back and forth for development, there is an expectation that the tool will automatically give the LLM a system prompt that potentiates its effectiveness and ability to help users save time, and minimizes its destructiveness and ability to waste users time. Well that last part seems like something isn’t working right or not “there” at all. It literally keeps deleting code. Why did I have to tell it not to. That should be the responsibility of the tool employed. The only other way to get it to not to delete code is to just send it all the code, but why would I do that? In that case, this tool becomes extremely expensive in terms of LLM cost, not to mention it makes things slower, and more prone to drift… since the LLM may hallucinate or change something random, like it did when it removed my word wrapping from an app.

**Comment by danenania** [comment]
I hear you--I'm working on improvements in this area.

**Comment by danenania** [comment]
@atljoseph  Should be better in 1.1.0 - https://github.com/plandex-ai/plandex/releases/tag/cli%2Fv1.1.0
