### ISSUE TITLE
Whitepaper Writing - plandex has trouble with staging changes to markdown files?

### ISSUE THREAD

**Issue by vessenes** [plandex-ai/plandex#15]
Dane, I LOVE this. I want to invest. :) 

I asked plandex to flesh out a plan to fill out a white paper, and it did a reasonable job of marshaling GPT-4 into suggestions and some step by step plans. All good. 

```bash
% plandex tell "Finish up the whitepaper in detail"         
✅ Context is up to date

 💬 User prompt 👇 

  Finish up the whitepaper in detail

 🤖 Plandex reply 👇 

  Given the nature of the task to finish up the whitepaper in detail, and     
  considering the provided context, this task involves expanding and          
  finalizing the document based on the sections outlined in the provided      
  markdown files. This task does not involve coding or system administration, 
  so the response will not include code blocks or file updates. Instead, I    
  will provide a detailed plan for completing the whitepaper, focusing on the 
  content and structure.                                                      
                                                                              
  ## Plan to Finish the Whitepaper in Detail                                  
                                                                              
  1. Expand the "Motivation" Section [snip]                   
  ```

However, it doesn't stage any changes -- I speculate that it's been designed for working with a codebase first? 

```bash
% plandex ch                                       
🤷‍♂️ No changes pending
```

Am I doing something wrong, or is this an edge case for plandex? There doesn't seem to be a good way to allow it to introspect, e.g. when I try:

```bash
plandex tell "Update the white paper per our conversation"
✅ Context is up to date

 💬 User prompt 👇 

  Update the white paper per our conversation

 🤖 Plandex reply 👇 

  I need more information or context to make a plan for this task.            
  Specifically, could you please clarify the updates or changes you would like
  to make to the whitepaper based on our conversation?                        

 plandex (ch)anges  👉 review plan changes
 plandex (ap)ply  👉 apply plan changes to project files
 plandex log  👉 show log of plan updates
 plandex rewind (rw)  👉 rewind to a previous state
```

**Comment by danenania** [comment]
Thank you @vessenes!

Did you load the whitepaper file into context first? You could try giving it more explicit instructions that you want to it update (or output) a file.

**Comment by vessenes** [comment]
Yes, it was loaded into context as a first step. 

Yes, with more explicit instructions it seems to be willing to update a markdown file. Close this bug away whenever you like of course, but I guess I'd update it to a UI bug/infrastructure request, which is that you allow plandex to review the conversation history. Plandex goes ahead and chats to GPT-4 and makes a plan, but there isn't a way to specifically ask it to refer to / incorporate that feedback in a next request right now as far as I can tell.

**Comment by danenania** [comment]
@vessenes Ok, thanks for that info and the update. I may not be understanding, but Plandex does maintain the conversation history in its context. You should be able to make references to earlier messages.

```bash
plandex tell "update whitepaper.md with the following changes..."
plandex tell "actually, redo whitepaper.md -- follow the earlier instructions I gave, but also do this..."
```

That should work. Or did mean something else?

**Comment by vessenes** [comment]
Hmm. In my posted chat log above, the last one, you can see I asked to it to make the updates from our conversation and it was like "which ones?" It had a long list of actionable next steps in the original convo. If it's offering former conversation output to GPT-4 as context, then I guess it was just a bad random outcome from text generation. But it looked like from the conversation that it wasn't. 

In your example, does the second tell take any intermediate output from plandex's conversation with GPT-4 from the first tell? Or does it remember the first tell, but not the 'narrative' responses when it's looking at your instructions?

**Comment by vessenes** [comment]
To add clarity, you're referring to your prior instructions. In practice, after that first tell there's a sort of back and forth Chain-Of-Thought/Planning thing you do with GPT-4 to get action steps. It is those steps I suggest be (optionally?) made available for later 'tell's.

**Comment by danenania** [comment]
The whole conversation, including back-and-forth, all stays in the context up to the `Max Convo Tokens` setting from `plandex models`, at which point summaries are gradually subbed in for earlier messages to keep it under the limit. But the default for `Max Convo Tokens` is 10000 tokens, which is quite a long conversation, so I don't think you'd be running into that in your example.

My guess is that gpt-4 either "forgot" the context, which can definitely happen, or else it 'decided' that `Update the white paper per our conversation` was too ambiguous. In general, it tends to do better when you really spell things out.

**Comment by vessenes** [comment]
Got it, thanks. I've run this test on the same file four or five times now in clean directories, and I can get it to work by being *very* specific that I want it to edit a particular markdown file. Otherwise I get a refusal -- "this is a big project, here's a bulleted list of things we should do" -> no changes queued. 

Sample failure tell: (this will not actually write anything)

```bash
% plandex tell "Flesh out and write the whitepaper for me."   
```

Sample successful tell: (this does queue patches against the markdown file)

```bash
% plandex tell "Flesh out and Write the whitepaper for me by actually changing the text of the markdown file"
```

In the refusal scenario, I do see it working with the file if I specifically request it to later, although it often does only roughly 1/5 of the recommended changes - I would guess this is context length related based on your explanation. 

I can't help but feel my original complaint stands, which is that plandex is less than 'magical' in terms of instruction following when we get a bit out of the "edit / fix this code" realm and into other forms of manipulating text files. But that's no doubt a matter of taste and focus.

**Comment by danenania** [comment]
Thanks, it's a valid critique. Specifically labelling the files in prompts definitely helps. So yes "Update 'whitepaper.md' with these changes..." is better than "Update the whitepaper". 

The behavior where it lists out steps but then doesn't actually do them is very annoying. There seems to be an inherent amount of laziness, at least in gpt-4, that causes this occur periodically despite a lot of instructions in the prompt to *not* do that.

I think you're also onto something with the idea that there is a tension between being good at less clearly defined and code-oriented and being good at coding tasks. The prompts are definitely geared toward the latter. In the future, I'd like to explore using a model call to categorize the initial prompt and then load a different set of prompts for the core planning behavior depending on the type of task.

Thanks again for reporting on your explorations. Getting all this data from real world usage (vs. mainly my own testing) is very enlightening.

**Comment by cocobeach** [comment]
> It could be Claude is less lazy also -- I certainly see more complete code responses from Claude 3 -- anyway. Keep me posted when you decide to raise. :)

Agreed, Claude is more productive, GPT4 seems lazy sometimes.

Having said that, what could be the reason that after creating a new project in a new dir, it won;t load any context, it reads it apparently but does nothing with it, and answers: "no context loaded" ?
