### ISSUE TITLE
How to use Gemini

### ISSUE THREAD

**Issue by BananaBake** [plandex-ai/plandex#165]
Hi. This looks very cool. In the docs, I saw you can use Gemini as well. Could you please explain to me how to do that? I am looking forward to testing this out, but I don't have an openAI account. Thanks very much.

**Comment by danenania** [comment]
Hey @BananaBake, check this out for details on using custom models: https://github.com/plandex-ai/plandex/blob/main/guides/USAGE.md#model-settings-

https://openrouter.ai/ has Gemini. Just a warning though that when I tried it a couple months ago, reliability wasn't very good. 

While non-OpenAI models are fully supported, lack of reliable function-calling and other reliability issues mean they should generally be considered experimental for now. I expect this will change before too long.

**Comment by BananaBake** [comment]
@danenania Thanks
