### ISSUE TITLE
Json: cannot unmarshal string into Go struct field ChangesWithLineNums.changes of type []*shared.StreamedChangeWithLineNums

### ISSUE THREAD

**Issue by achristianson** [plandex-ai/plandex#173]
Getting this any time I try to do a `plandex tell`:

```
🚨 Server error
  → Error unmarshalling build response
    → Json: cannot unmarshal string into Go struct field ChangesWithLineNums.changes of type []*shared.StreamedChangeWithLineNums
```

It gets through the planning process, starts making changes, and then at some point while/shortly after making changes, it gives this error.

I'm using openrouter with `anthropic-claude-3.5-sonnet`.

**Comment by achristianson** [comment]
Just switched to `gpt-4o-latest` and didn't get the error, so it *might* have to do with model selection.

**Comment by danenania** [comment]
This error means that the model couldn’t generate valid JSON for a function call despite multiple retries. Unfortunately Claude Sonnet, despite its generally impressive capabilities, still has this issue quite frequently.

For now I’d recommend using the built-in mixed Claude/OpenAI model pack (`anthropic-claude-3.5-sonnet-gpt-4o` that uses Claude for planning and summaries, and gpt-4o for everything else. This gives you the benefits of sonnet’s reasoning and coding abilities plus the better function calling reliability of the OpenAI models.

**Comment by achristianson** [comment]
OK good to know, thanks!
