### ISSUE TITLE
Request: support installation

### ISSUE THREAD

**Issue by viraptor** [plandex-ai/plandex#177]
I'm starting a new plandex server using:
```
DATABASE_URL='postgres://plandex@localhost/plandex?sslmode=disable' plandex-server
```
and get the following output:
```
2024/07/20 14:27:51 connected to database
2024/07/20 14:27:51 Error running migrations: error creating migration instance: open .: no such file or directory
```
There's no more output available for a better context unfortunately.

The migration table itself (`schema_migrations`) gets created correctly.

Version 1.1.1

**Comment by viraptor** [comment]
It looks like it's related to https://github.com/golang-migrate/migrate/issues/1112

The [path in the source](https://github.com/plandex-ai/plandex/blob/59bf40e678f5cbf85ee7b3cb625469093eab46b1/app/server/db/db.go#L67) points to some relative `migrations` directory which may not exist unless the app is run directly from the development location.

It would be great if plandex supported installation.

**Comment by danenania** [comment]
Hey @viraptor, currently the server isn't designed to run as a standalone binary outside the context of the repo or a docker container, partly due to requiring the migrations directory. Check out the [self-hosting docs](https://docs.plandex.ai/hosting/self-hosting) for the various options.
