### ISSUE TITLE
Unable to build cli/v0.8.1

### ISSUE THREAD

**Issue by davidgarciaMontreal** [plandex-ai/plandex#19]
Hello, I attempted to install the Plandex CLI by following the provided steps. However, I encountered an error during the build process:

`2024-04-03 22:21:31 egasdad@DESKTOP-QD0B380:~/git/plandex/app/cli$ go build
term/select.go:8:2: github.com/plandex-ai/survey/v2@v2.0.0-00010101000000-000000000000: replacement directory ../../../survey does not exist`

Additionally, here is the version of Go I am using:

`2024-04-03 22:21:34 egasdad@DESKTOP-QD0B380:~/git/plandex/app/cli$ go version
go version go1.21.3 linux/amd64`

commit:
`2024-04-03 22:21:44 egasdad@DESKTOP-QD0B380:~/git/plandex/app/cli$ git show
commit 1d0d8e0d495ec454a5170cf9d2a7157f76ee793a (HEAD -> main, tag: cli/v0.8.1, origin/main, origin/HEAD)
Author: Dane Schneider <dane@envkey.com>
Date:   Wed Apr 3 07:52:20 2024 -0700 Bump version to 0.8.1`
Could anyone provide assistance or guidance on resolving this issue?

**Comment by danenania** [comment]
Ah, that's because a required dependency (https://github.com/plandex-ai/survey) is missing from the build instructions. It should be cloned into the same directory as this repo, so that `plandex` and `survey` are sibling directories:

```
git clone https://github.com/plandex-ai/plandex.git
git clone https://github.com/plandex-ai/survey.git
cd plandex/app/cli
go build -ldflags "-X plandex/version.Version=$(cat version.txt)"
mv plandex /usr/local/bin # adapt as needed for your system
```

I'll update the README.md

**Comment by davidgarciaMontreal** [comment]
@danenania thank you!
