### ISSUE TITLE
Ollama integration

### ISSUE THREAD

**Issue by tinkerbaj** [plandex-ai/plandex#20]
Is there a plan for ollama integration?

**Comment by danenania** [comment]
Yes, I want to add support for as many models as possible.

Would this be covered by allowing custom OpenAI endpoints as described in #16? Does anyone know if ollama is fully compatible with the OpenAI API or where I can find a list of what is and isn't supported?

**Comment by danenania** [comment]
Ok, it looks like it doesn't yet support function calling. Once it does, it should be straightforward to add it.

**Comment by imhsouna** [comment]
what about lm studio

**Comment by knno** [comment]
Regarding LM Studio I was trying to integrate it but was getting:

`[Server Error] {"title":"'messages' array must only contain objects with a 'content' field that is not empty"}`

Because Plandex is sending empty messages:
```
    {
      "role": "assistant",
      "content": ""
    },
    {
      "role": "assistant",
      "content": ""
    },
    ...
```
Not sure how to prevent this

**Comment by danenania** [comment]
As of 0.9.0 (https://github.com/plandex-ai/plandex/releases/tag/cli%2Fv0.9.0) Plandex can now be used with any OpenAI-compatible models, including Ollama -- check the release notes for more details on this, and please lmk how it goes if you try it!

**Comment by tcsenpai** [comment]
Hello, sorry to reopen this @danenania 

I can't find the way to set up the custom OpenAI url needed to work with ollama.

Can you please elaborate on the set-model command to use?
