### ISSUE TITLE
Permission error while running install script

### ISSUE THREAD

**Issue by Julioevm** [plandex-ai/plandex#21]
Hey, very interesting project!

I tried running the install script `curl -sL https://plandex.ai/install.sh | bash` on a Mac m1 and I got the following error:

```Plandex 0.8.1 Quick Install
Copyright (c) 2024 Plandex Inc.

Downloading Plandex tarball from https://github.com/plandex-ai/plandex/releases/download/cli%2Fv0.8.1/plandex_0.8.1_darwin_arm64.tar.gz
mv: rename plandex to /usr/local/bin/plandex: Permission denied```

**Comment by retendo** [comment]
You need to have admin rights to move something into /usr/local/bin.  The install script tries to do that, so you should probably try running the command with sudo.

**Comment by aspectaurora** [comment]
To ensure the entire script runs with elevated privileges, you can try downloading the script first, then executing it with sudo. Here's how you can do it:
 ```
 curl -sL https://plandex.ai/install.sh -o install_plandex.sh
chmod +x install_plandex.sh
sudo ./install_plandex.sh
 ```

**Comment by aakashb09** [comment]
but for every invocation of plandex command, you would encounter permission issues on `~/.plandex-home` and `logs`.

**Comment by danenania** [comment]
Should now be fixed!
