### ISSUE TITLE
help appears twice in available commands

### ISSUE THREAD

**Issue by ChrisOboe** [plandex-ai/plandex#25]
plandex -h
Usage:
  plandex [command] [flags]
  plandex [command]

Available Commands:
  apply         Apply a plan to the project
  branches      List plan branches
  build         Build pending changes
  cd            Set current plan by name or index
  changes       View, copy, or manage changes for the current plan
  checkout      Checkout an existing plan branch or create a new one
  clear         Clear all context
  completion    Generate the autocompletion script for the specified shell
  connect       Connect to an active stream
  continue      Continue the plan
  convo         Display complete conversation history
  current       Get the current plan
  delete-branch Delete a plan branch by name or index
  delete-plan   Delete a plan by name or index, or delete all plans with --all flag
  **help          Display help for Plandex**
  **help          Help about any command**
  invite        Invite a new user to the org
  load          Load context from various inputs
  log           Show plan history
  ls            List everything in context
  models        Show model settings
  new           Start a new plan
  plans         List all available plans
  ps            List plans with active or recently finished streams
  revoke        Revoke an invite or remove a user from the org
  rewind        Rewind the plan to an earlier state
  rm            Remove context
  set-model     Update model settings
  sign-in       Sign in to a Plandex account
  stop          Connect to an active stream
  tell          Send a prompt for the current plan
  update        Update outdated context
  users         List all users and pending invites and the current org
  version       Print the version number of Plandex

Flags:
  -h, --help   help for plandex

Use "plandex [command] --help" for more information about a command.

**Comment by danenania** [comment]
Thanks, the install script should actually use the `plandex help` command rather than `plandex -h`. I'll fix that.

**Comment by danenania** [comment]
Also will override `plandex --help / -h` to show the custom help command instead of cobra's default help.
