### ISSUE TITLE
claude integration

### ISSUE THREAD

**Issue by qume** [plandex-ai/plandex#27]
So happy to find this, I wrote and am using something similar, which I'll now ditch for this.

I used an external command line tool (https://llm.datasette.io/) so I could use different LLMs and compare them, and Claude Opus was better probably 80% of the time than GPT4 (I was doing pretty much all my tests in both in parallel). When Claude wasn't better, they were roughly even. There might have been one or two instances where GPT4 was better, but nothing notable. 

Anyway, wanted to mention this because you might want to bump up the priority of supporting Claude, or using a third party lib like I did to abstract the LLMs away. This will give your project a real boost... until GPT5 switches it around inevitably of course

**Comment by ma-abdellaoui** [comment]
I also had very similar observations. I am a ML Eng. and I use LLMs daily for my work. Using the exact same prompts, the output of Claude is much more structured and direct that gpt4 around 80% of the time.
  
It would a huge bump to the project if we can get Claude integration into this.

**Comment by danenania** [comment]
This is definitely on the short term roadmap 👍

**Comment by danenania** [comment]
@qume @ma-abdellaoui Claude is now supported via OpenRouter.ai! Just make an OpenRouter account/api key and then use `plandex set-model` to try it. I've been playing with it and results are impressive so far.

![plandex-models](https://github.com/plandex-ai/plandex/assets/545350/6cf8ed5c-8453-407f-865f-c98febed3628)
