### ISSUE TITLE
tmux

### ISSUE THREAD

**Issue by qume** [plandex-ai/plandex#28]
When using it in tmux, plandex apply gives the following:

```
                                        🚨 Failed to get confirmation user input
  → Failed to get user input
    → Failed to open keyboard
      → Error while reading terminfo data:termbox
        → Unsupported terminal
```

Today I found out there are CLI nerds out there who don't use tmux!

**Comment by jumski** [comment]
I have same problem and i confirm running it in kitty without tmux solves it.

```
tmux 3.4.4
kitty 0.31.0
fish shell 3.7.0
```

**Comment by harleypig** [comment]
I run tmux and am not having any issues.

- What operating system?
- What version of plandex?
- What command are you running?
- What shell?
- What's your TERM set to?

**Comment by danenania** [comment]
@qume Is this still an issue for you?

**Comment by smantzavinos** [comment]
I'm still seeing this issue running tmux in kitty terminal on nixos. TERM is set to "tmux-256color". 

Should I open an new issue for this?
