### ISSUE TITLE
LiteLLM support (Ollama, Claude, Azure OpenAI, Gemini, etc)

### ISSUE THREAD

**Issue by pablospe** [plandex-ai/plandex#30]
In order to support Ollama, Claude, Azure OpenAI, Gemini, etc. (see [supported providers](https://github.com/BerriAI/litellm?tab=readme-ov-file#supported-providers-docs)) one could use [LiteLLM](litellm.ai), which it is very easy to use. Documentation:
https://docs.litellm.ai/docs

This will cover these issues too:
https://github.com/plandex-ai/plandex/issues/20
https://github.com/plandex-ai/plandex/issues/27

**Comment by danenania** [comment]
Thanks for the suggestion. In order for it to be a drop-in replacement, it would need to support function calls, and beyond that streaming function calls. I do want to add more models as soon as it's feasible.

**Comment by pablospe** [comment]
In case it helps:
* https://docs.litellm.ai/docs/completion/function_call
* https://docs.litellm.ai/docs/completion/stream

**Comment by danenania** [comment]
@pablospe @aldoyh 0.9.0 allows for using models from any OpenAI-compatible provider, including LiteLLM. That said, in my own testing I've found OpenRouter.ai to be easier in terms of a drop-in replacement.

**Comment by maelp** [comment]
would it make sense to instead base the code on MCP and then be able to use any model?
