### ISSUE TITLE
Error getting plan, context, convo, or summaries

### ISSUE THREAD

**Issue by Dexus** [plandex-ai/plandex#32]
```
$ plandex t --file promt/p1-golang.txt
✅ Context is up to date
� Server error
  → Error getting plan, context, convo, or summaries
```

using alpine linux

**Comment by danenania** [comment]
Thanks for reporting @Dexus. I'll get this error message fixed

**Comment by viperfx** [comment]
Seeing a similar issue. Is it seems like an issue with Plandex cloud?

**Comment by danenania** [comment]
@viperfx The underlying error message isn't getting through (I'm working on a fix for that), but is most commonly a 401 from OpenAI when an API key is invalid or out of credits.

**Comment by urstrulysv** [comment]
Confirmed, @danenania  The issue is indeed attributable to insufficient API credits. I trust this information will be instrumental in resolving the code

**Comment by burkayedu** [comment]
same issue on wsl
