### ISSUE TITLE
Can't build for NixOS: ../../../survey does not exist

### ISSUE THREAD

**Issue by mrdev023** [plandex-ai/plandex#33]
I get the following error.

```bash
       > go: plandex/term imports
       >        github.com/plandex-ai/survey/v2: github.com/plandex-ai/survey/v2@v2.0.0-00010101000000-000000000000: replacement directory ../../../survey does not exist
```

Package file

```nix
{
  lib,
  fetchFromGitHub,
  buildGoModule
}:

buildGoModule {
  pname = "plandex-cli";
  version = "v0.8.1";
  vendorHash = lib.fakeHash;
  src = fetchFromGitHub {
    owner = "plandex-ai";
    repo = "plandex";
    rev = "cli/v0.8.1";
    hash = "sha256-+1EETcqjvyi9W+y6nhcEFbc2bv2EjFEBxoxMrWPz7Ro=";
  };
  
  modRoot = "app/cli";
  
  meta = with lib; {
    description = "An AI coding engine for complex tasks";
    homepage = "https://github.com/plandex-ai/plandex";
    license = licenses.agpl3Only;
  };
}
```

**Comment by danenania** [comment]
I have never gotten around to giving Nix a try so I'm not familiar with it, but the plandex CLI has a dependency on a fork of a library called `survey` that it expects to be in a sibling directory to the `plandex` directory when building:

```
git clone https://github.com/plandex-ai/plandex.git
git clone https://github.com/plandex-ai/survey.git
cd plandex/app/cli
go build -ldflags "-X plandex/version.Version=$(cat version.txt)"
mv plandex /usr/local/bin # adapt as needed for your system
```

Can this be incorporated into the Nix config somehow?

**Comment by mrdev023** [comment]
> I have never gotten around to giving Nix a try so I'm not familiar with it, but the plandex CLI has a dependency on a fork of a library called `survey` that it expects to be in a sibling directory to the `plandex` directory when building:
> 
> ```
> git clone https://github.com/plandex-ai/plandex.git
> git clone https://github.com/plandex-ai/survey.git
> cd plandex/app/cli
> go build -ldflags "-X plandex/version.Version=$(cat version.txt)"
> mv plandex /usr/local/bin # adapt as needed for your system
> ```
> 
> Can this be incorporated into the Nix config somehow?

I can't if is not included in src

**Comment by mrdev023** [comment]
but in submodule i can

**Comment by mrdev023** [comment]
Oh wait i try something https://discourse.nixos.org/t/how-to-create-package-with-multiple-sources/9308/2

**Comment by danenania** [comment]
Ok, I'd prefer not to have to mess around with submodules, but can do that if necessary.

I'm also probably to sub in a different library for `survey` at some point--https://github.com/charmbracelet/huh, so that could be a way to resolve this as well.

**Comment by mrdev023** [comment]
> Ok, I'd prefer not to have to mess around with submodules, but can do that if necessary.
> 
> I'm also probably going to sub in a different library for `survey` at some point--https://github.com/charmbracelet/huh, so that could be a way to resolve this as well.

Yes i think but you can't use you repo instead of local folder ?

**Comment by mrdev023** [comment]
This patch https://github.com/plandex-ai/plandex/commit/18da990f9cea059015b93e76420d14205a43a876

With 

```nix
{
  lib,
  fetchFromGitHub,
  buildGoModule
}:

buildGoModule rec {
  pname = "plandex-cli";
  version = "v0.8.2";

  vendorHash = "sha256-+giOD3sB/SnyccFqoGnC2+DVR9u+MF+mqTFSoEEQqRw=";

  src = fetchFromGitHub {
    owner = "mrdev023";
    repo = "plandex";
    rev = "18da990f9cea059015b93e76420d14205a43a876";
    hash = "sha256-bHbPN8b3k4K2V5ul17U8O6RjBQdT3xT1I31Pe94Q52c=";
  };

  modRoot = "app/cli";

  meta = with lib; {
    description = "An AI coding engine for complex tasks";
    homepage = "https://github.com/plandex-ai/plandex";
    license = licenses.agpl3Only;
  };
}
```

Work well

**Comment by mattchrist** [comment]
@mrdev023 I have a draft PR to nixpkgs to add both the client and server.

Client is packaged here: https://github.com/NixOS/nixpkgs/pull/304645/files#diff-7030184c67ecd7b20637f34138ceaf60746fd3c3401da0d4b843f344fb489b72

**Comment by mahmoodfateh** [comment]
https://github.com/Nixos/nixpkgs/pull/

**Comment by mrdev023** [comment]
> @mrdev023 I have a draft PR to nixpkgs to add both the client and server.
> 
> Client is packaged here: https://github.com/NixOS/nixpkgs/pull/304645/files#diff-7030184c67ecd7b20637f34138ceaf60746fd3c3401da0d4b843f344fb489b72

Thx i try it later but it look good to me. Good job 😁
