### ISSUE TITLE
Docker Compose user authentication failed

### ISSUE THREAD

**Issue by arnavmehta7** [plandex-ai/plandex#36]
Hey, I was trying this out and struck with this issue.
```
 ! plandex-server The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                  0.0s 
Attaching to plandex-postgres-1, plandex-server-1
plandex-postgres-1  | 
plandex-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
plandex-postgres-1  | 
plandex-postgres-1  | 2024-04-05 18:14:48.264 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
plandex-postgres-1  | 2024-04-05 18:14:48.264 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
plandex-postgres-1  | 2024-04-05 18:14:48.264 UTC [1] LOG:  listening on IPv6 address "::", port 5432
plandex-postgres-1  | 2024-04-05 18:14:48.265 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
plandex-postgres-1  | 2024-04-05 18:14:48.269 UTC [30] LOG:  database system was shut down at 2024-04-05 18:14:09 UTC
plandex-postgres-1  | 2024-04-05 18:14:48.278 UTC [1] LOG:  database system is ready to accept connections
plandex-server-1    | wait-for-it.sh: waiting 15 seconds for plandex-postgres:5432
plandex-server-1    | wait-for-it.sh: plandex-postgres:5432 is available after 0 seconds
plandex-postgres-1  | 2024-04-05 18:14:52.543 UTC [35] FATAL:  password authentication failed for user "user"
plandex-postgres-1  | 2024-04-05 18:14:52.543 UTC [35] DETAIL:  Role "user" does not exist.
plandex-postgres-1  | 	Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
plandex-server-1    | 2024/04/05 18:14:52 Error initializing database: pq: password authentication failed for user "user"
```

I set my .env to this:
```
POSTGRES_PASSWORD=password
PLANDEX_DB=plandex
PLANDEX_USER=user
PLANDEX_PASSWORD=password
PGDATA_DIR=./datadir
PLANDEX_DATA_DIR=./pdatadir
GOENV=development
PIN2LOG=true
```
I tried different variations/values but still same issue. Can someone please help me to figure out what's wrong?

**Comment by Fuccyou123** [comment]
https://github.com/plandex-ai/plandex/issues/36#issue-2228568360 #27 #32  ! plandex-server The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                  0.0s 
Attaching to plandex-postgres-1, plandex-server-1
plandex-postgres-1  | 
plandex-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
plandex-postgres-1  | 
plandex-postgres-1  | 2024-04-05 18:14:48.264 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
plandex-postgres-1  | 2024-04-05 18:14:48.264 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
plandex-postgres-1  | 2024-04-05 18:14:48.264 UTC [1] LOG:  listening on IPv6 address "::", port 5432
plandex-postgres-1  | 2024-04-05 18:14:48.265 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
plandex-postgres-1  | 2024-04-05 18:14:48.269 UTC [30] LOG:  database system was shut down at 2024-04-05 18:14:09 UTC
plandex-postgres-1  | 2024-04-05 18:14:48.278 UTC [1] LOG:  database system is ready to accept connections
plandex-server-1    | wait-for-it.sh: waiting 15 seconds for plandex-postgres:5432
plandex-server-1    | wait-for-it.sh: plandex-postgres:5432 is available after 0 seconds
plandex-postgres-1  | 2024-04-05 18:14:52.543 UTC [35] FATAL:  password authentication failed for user "user"
plandex-postgres-1  | 2024-04-05 18:14:52.543 UTC [35] DETAIL:  Role "user" does not exist.
plandex-postgres-1  | 	Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
plandex-server-1    | 2024/04/05 18:14:52 Error initializing database: pq: password authentication failed for user "user"

**Comment by harleypig** [comment]
```
plandex-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
```
Either you're using an existing postgres installation or the first-time init was interrupted.

If you're using an existing installation, you'll need to create your user manually first. If you're using a new installation, delete the data files (in PGDATA_DIR) run it again.

**Comment by danenania** [comment]
@arnavmehta7 Closing for now, but let me know if @harleypig's response didn't resolve and I'll reopen.
