### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by Umang7198** [plandex-ai/plandex#4]
I have installed plandex in my windows PC, But I am unable to login 
![Uploading Screenshot 2024-03-30 210000.png…]()
I am getting this type of error while logging in.
How can I solve this problem ?

**Comment by danenania** [comment]
Hey @Umang7198 I can't see your screenshot. Could you try uploading it again?

**Comment by danenania** [comment]
@Umang7198 closing for now, but please let me know if you're still seeing the issue and can reupload the screenshot, and I'll re-open.
