### ISSUE TITLE
Consistent Server Error Encountered When Interacting with Plandex

### ISSUE THREAD

**Issue by urstrulysv** [plandex-ai/plandex#49]
I am experiencing a consistent server error while attempting to interact with Plandex. Whenever I try to use the plandex tell command with a prompt, I receive the following error message:

🚨 Server error
  → Error getting plan, context, convo, or summaries

This error occurs consistently and prevents me from utilizing the Plandex service effectively. I have attempted to retry the command multiple times and have waited for some time before trying again, but the issue persists.

Expected Behavior:
I expect to receive assistance or suggestions from Plandex based on the provided prompt, as intended.

Actual Behavior:
Instead, I consistently encounter a server error, as described above.

Additional Information:

Operating System: macOS 
Plandex Version: latest
Internet Connection:  Wi-Fi, Ethernet

**Comment by danenania** [comment]
Hi @urstrulysv, this is the same issue as #32 – this is most likely a 401 from OpenAI due to an invalid key or lack of api credits, but the error message is not returned correctly. This will be fixed soon.

**Comment by urstrulysv** [comment]
Yes, @danenania , it appears that the issue stems from a deficiency in API credits on my end.
