### ISSUE TITLE
Simple CRUD request, makes multiple steps and deletes all other code that is already present, or in a previous step created.

### ISSUE THREAD

**Issue by Dexus** [plandex-ai/plandex#54]
Hi,

a simple CRUD request creates the functions in several steps, but deletes other existing functions and/or those created from the previous step in the same file.

Example of a user model: 
- Step1: 14 lines added, 50 deleted that already existed 
- Step2: the previously created 14 lines deleted and 6 new ones added -> but different functions (deleted CreateUser and database connection - added UpdateUser) 
- Step3: the previously added UpdateUser replaced with a DeleteUser function.

Result currently unusable.

**Comment by danenania** [comment]
Thanks for reporting @Dexus. This is similar to #50 (file update problems) so I'll copy some of my response from there.

I'll investigate. Also please read [limitations and guideance](https://github.com/plandex-ai/plandex#limitationsand-guidance-%EF%B8%8F) section in the readme.

I'm working on improving file updates as much as possible, but they still aren't perfect. In cases where changes are applied incorrectly, I'd recommend using plandex changes to reject the change and apply it manually--you can either copy it from the plandex changes TUI or if it's incorrect there as well, use plandex convo to output the full conversation and copy it from there.

And I'll of course continue working to get updates as reliable as possible.

**Comment by danenania** [comment]
@Dexus these kinds of issues should be much rarer in 0.9.0 (https://github.com/plandex-ai/plandex/releases/tag/cli%2Fv0.9.0)
