### ISSUE TITLE
The same file can be added to context twice

### ISSUE THREAD

**Issue by JonatanE** [plandex-ai/plandex#57]
The same file can be added twice with plandex add.
When plandex rm is run on the filename, it reports removing it twice.

**Comment by danenania** [comment]
This might also be a good one for a contributor.

**Comment by abrl91** [comment]
Hey @danenania can you assign me to this issue?

**Comment by abrl91** [comment]
@danenania 
I couldn't reproduce this issue
![image](https://github.com/plandex-ai/plandex/assets/39680385/06286426-1ef7-4b4f-a0ad-2d70dd8be77b)

@JonatanE can you provide steps to reproduce?

**Comment by JonatanE** [comment]
![image](https://github.com/plandex-ai/plandex/assets/5001585/80e68339-e352-4d15-aa5f-2a87cccb00f0)
It also doesn't seem to update and notifies my in every action. I press "y" to update but it doesnt seem to work.

**Comment by JonatanE** [comment]
I'm on WSL2, arch linux btw
