### ISSUE TITLE
Server error → Error getting plan, context, convo, or summaries

### ISSUE THREAD

**Issue by LeVietHa05** [plandex-ai/plandex#67]
"→ Error getting plan, context, convo, or summaries"
  i got this error when try using tell for the first time after loaded all the context needed

**Comment by mo-mughrabi** [comment]
Same here, anyway to view the full error trace?

**Comment by LeRatierBretonnien** [comment]
Same here

**Comment by bandi13** [comment]
Same issue. I am trying with the free version. I'll try to use my API key.

**Comment by danenania** [comment]
This is a duplicate of #32.

It's most likely caused by either an invalid OpenAI api key or not having OpenAI credits. The error message will be fixed in the next release.
