### ISSUE TITLE
`set-model` command isn't parsing arguments correctly to set a new model for a specific role

### ISSUE THREAD

**Issue by danenania** [plandex-ai/plandex#75]
`plandex set-model` with no arguments is working correctly and prompts the user to update model settings or select a role to a set a new model for, but when passing arguments like this: `plandex set-model planner gpt-4`, it isn't updating correctly.

Likely a problem in argument parsing in the CLI command, since if there was a problem on the server, it would be impacting the no arguments form as well.

**Comment by ADTmux** [comment]
Hey, I would like to work on this

**Comment by danenania** [comment]
@ADTmux Awesome, thank you! I assigned it to you.

**Comment by ADTmux** [comment]
Hey @danenania , I've got an issue while setting up reflex (from [)](https://github.com/ADTmux/plandex/blob/main/guides/DEVELOPMENT.md), 
<img width="524" alt="Screenshot 2024-04-10 at 7 23 26 PM" src="https://github.com/plandex-ai/plandex/assets/165437009/c4b5adaa-fbb0-4d73-8d79-404dbfb0e501">

I also tried [https://github.com/cespare/reflex/issues/26](url)
My setup is macOS 14.4.1 (Intel), any suggestions?

**Comment by danenania** [comment]
@ADTmux probably you need to add `$GOPATH/bin` to your $PATH.
