### ISSUE TITLE
pdx apply，No changes pending

### ISSUE THREAD

**Issue by CUIT-fenghuiyu** [plandex-ai/plandex#82]
After completing the task，pdx apply，show "No changes pending"
![联想截图_20240412124139](https://github.com/plandex-ai/plandex/assets/79908875/42d5e190-05b5-42a9-b2d2-d95094c1f6ab)

**Comment by danenania** [comment]
Hmm. First thing is that `plandex tell` is designed to accept _either_ a `--file` parameter or an inline prompt, though that doesn't explain the lack of pending changes.

Also if you wanted to update a file, the typical way would be to use `plandex load test.txt` to add the file to context first before using `plandex tell`. See https://github.com/plandex-ai/plandex/blob/main/guides/USAGE.md

Did you get a `missing file` prompt during the plan stream by any chance?
