### ISSUE TITLE
no changes pending

### ISSUE THREAD

**Issue by RTException** [plandex-ai/plandex#96]
![image](https://github.com/plandex-ai/plandex/assets/146321368/cc529b3c-0bb6-45b4-ae73-235077bd939e)
After executing `plandex tell --file task.txt` and then running the command `plandex changes`, why does it display `No changes pending`? How can I write the generated files into the current project directory? 
The content of task.txt is `Let's create a basic snake game using H5. Create all the files for the project so that it will be ready to compile and run.`

**Comment by RTException** [comment]
Thank you @danenania , I use plandex cloud, I have changed all the models to gpt-3.5-turbo.
Below are all the screenshots of the output and logs:

<img width="757" alt="plandex-console" src="https://github.com/plandex-ai/plandex/assets/146321368/6cdcf027-5363-4993-8c5c-4090258f6e5d">

![plandex-logs](https://github.com/plandex-ai/plandex/assets/146321368/ca0ad0a3-8f70-4f6c-84a8-4d588320917b)

**Comment by danenania** [comment]
![CleanShot 2024-04-20 at 08 47 41@2x](https://github.com/plandex-ai/plandex/assets/545350/54769037-c121-42e2-b28d-66b8285d50bc)

This looks like the problem... basically, the model didn't follow instructions in labelling the files, so they got generated as empty files. While this can happen occasionally even with `gpt-4-turbo`, it's pretty rare, but with `gpt-3.5-turbo` there are likely to be a lot more problems like this.

The model is instructed multiple times in the built-in prompts to follow the format, but you could try reinforcing it even more in your prompt by telling it something like "You MUST follow your instructions for labelling files EXACTLY". But overall I think 3.5 just isn't smart enough for the `planner` role and you are likely to see a lot of problems like this.
