### ISSUE TITLE
Automatic CLI upgrade isn't working in some cases

### ISSUE THREAD

**Issue by danenania** [plandex-ai/plandex#97]
I've had reports of it failing on WSL and Pop!_OS.

If anyone else has this issue, you can work around it in the meantime by re-installing the same way you installed the CLI initially.

**Comment by danenania** [comment]
Update: apparently running with `sudo` can resolve this, so it will likely just be necessary to detect the permissions error and suggest re-running with `sudo`.

**Comment by kalil0321** [comment]
Hi @danenania, I would like to work on this.

**Comment by danenania** [comment]
@kalil0321 Great, thank you! I assigned it to you.
